### ISSUE TITLE
如果断开client 之后， server 就会占用大量CPU

### ISSUE THREAD

**Issue by heartacker** [HandyOrg/HandyIpc#19]
如果client 程序关闭后，server 会占用大量CPU. 
![image](https://user-images.githubusercontent.com/1876302/164565581-a402ef73-cab9-4158-94d1-056a345c66e0.png)

![image](https://user-images.githubusercontent.com/1876302/164565644-e744f1dc-947d-4b27-a235-cc84a9331a32.png)

实在是找不到原因，

**Comment by DingpingZhang** [comment]
请提供一个最小复现 Demo，我这里无法复现此问题。
断开客户端后，服务器一直是 0%。

![image](https://user-images.githubusercontent.com/8541016/164614681-88fb1408-fc38-47f9-8f1e-4c1cfe5074de.png)

**Comment by Lizhengbo0304** [comment]
Net462确实不会出现这种情况，如果你把这个示例的环境切换到Net6.0，就会成功复现出来了，不知道有没有什么好的办法解决这个问题

**Comment by heartacker** [comment]
> Net462确实不会出现这种情况，如果你把这个示例的环境切换到Net6.0，就会成功复现出来了，不知道有没有什么好的办法解决这个问题

你也遇到这个问题吗？

**Comment by Lizhengbo0304** [comment]
> 

是的，我今天用到自己的项目上发现CPU占用异常，下了你的TestHandyIpc进行测试，发现CPU很正常，但是切换到Net6.0就会出现这种情况

**Comment by Lizhengbo0304** [comment]
> Net462不会出现这种情况，如果你把这个示例的环境切换到Net6.0，就可以复现出来了，不知道有没有什么好的
> 
> 你也遇到了这个问题吗？


是的，今天专门测试了几种环境才发现的，你的问题解决了吗

**Comment by heartacker** [comment]
没有

**Comment by DingpingZhang** [comment]
@heartacker @Lizhengbo0304 
Hi All,

已修复，请更新 `HandyIpc` 到 `0.5.3`（仅需更新它，`HandyIpc.NamedPipe` 等无需更新）。

该 bug 出现在 `.Net 6.0` 中的 `NamedPipe` 上，其行为与 `<= .Net 48` 不一致：在 `.Net Fx` 中，Client 关闭后，Server 的连接将立刻返回 0 bytes，并且**再次读取该 connection，将抛出以下异常**，而使得该 connection 被关闭、释放。

```
ArgumentException: Either the IAsyncResult object did not come from the corresponding async method on this type, or EndRead was called multiple times with the same IAsyncResult.
```

而在 `.Net 6.0` 中，Client 关闭后，也将立刻返回 0 bytes，但再次读取该 connection，将**不会抛出任何异常**，而且一直返回 0 bytes（`ReadAsync()` 不会阻塞），就导致服务端一直在空跑。

此问题不会在 Socket 中发生，因为无论 `.Net 6.0/Fx`，关闭 Client 后都会导致服务端立刻抛出以下异常：
```
IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
```
