### ISSUE TITLE
在Net6环境下，Client关闭后，服务占用的CPU居高不下

### ISSUE THREAD

**Issue by Lizhengbo0304** [HandyOrg/HandyIpc#22]
之前问题回答中提供的TestHandyIpc示例，在Net462下是正常的，切换到Net6.0之后，如果关闭Client，服务占用的CPU会飙升到30%~50%左右
![image](https://user-images.githubusercontent.com/15277601/186594122-8008ca5d-9055-4324-b455-1dcf62333eaa.png)

**Comment by DingpingZhang** [comment]
我得看一下，之前确实没有测试过 .net core 的情况

**Comment by Lizhengbo0304** [comment]
> 我得看一下，之前确实没有测试过 .net core 的情况

我尝试过在客户端断开之前，把服务Stop并重新Start，这时候CPU会恢复正常，但是下一个客户端无法正常连接到服务，第二个才可以正常连接服务并调用

**Comment by DingpingZhang** [comment]
#19
