### ISSUE TITLE
是否可以尝试去掉System.ValueTuple？

### ISSUE THREAD

**Issue by ping9719** [HandyOrg/HandyIpc#24]
我自己试了一下更改源代码发现工作量太大了。.....
我知道 `(key, interfaceType, factory)` 这种写法很酷，但是有一个致命的问题。
我在net4.6.2里面生成的文件会造成非常多的依赖项...导致我项目非常的不干净。
其实你可以采用元祖`Tuple<int, int>`也是一样的。

![image](https://user-images.githubusercontent.com/9651046/200209989-c8865716-a80e-4a43-a550-66649050b70b.png)

**Comment by DingpingZhang** [comment]
这个问题的解决方案并不只有去掉 `System.ValueTuple`。

现在除了 `HandyIpc` 以外，其它包我没有 target 到 .net462，就像这样：

```xml
<TargetFrameworks>netstandard2.0;net462</TargetFrameworks>
```

此外，如果你的项目使用 .net472 也可以解决，现在 win10 都支持到 .net48。

**Comment by ping9719** [comment]
原来如此，那可以改成net<=461吗？这是一个很浩大的工程，我试了下这种方式不能编译通过
`<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>`
我确实框架改成net472，干净了很多
![image](https://user-images.githubusercontent.com/9651046/200459618-961ca818-2e4d-44fc-97f4-03055235e737.png)
