### ISSUE TITLE
内存是否哪里没有释放干净？

### ISSUE THREAD

**Issue by ping9719** [HandyOrg/HandyIpc#25]
服务端代码
``` CSharp
        static void Main(string[] args)
        {
            // 创建一个容器服务器 Builder。
            ContainerServerBuilder serverBuilder = new ContainerServerBuilder();
            serverBuilder.UseNamedPipe("JgkljServe").UseJsonSerializer();
            serverBuilder.Register<IHansLaserServe, HansLaserServe>();
            using (var server = serverBuilder.Build())
            {
                server.Start();

                //检查状态进行阻塞，降低CPU使用率
                while (server.IsRunning)
                    Task.Delay(1000).Wait();
            }
        }
```

启动时内存（2.8M）
![image](https://user-images.githubusercontent.com/9651046/200256291-cd775f72-1cc2-41fa-8a48-12aa0a0b0d28.png)
执行了50次方法后（4.8M）（我的方法是调用别人的dll，不存在自身的内存问题）
![image](https://user-images.githubusercontent.com/9651046/200256726-4fe8082e-bf77-4089-8725-9d5ef4647b85.png)

**Comment by DingpingZhang** [comment]
之后内存有继续往上涨吗？比如执行 500 次，1000 次后，内存涨到 30M，60M。

内存方面我没有相应的测试用例，但我写过 demo：同步多个 wpf 程序之间的鼠标移动事件，这个调用量是比较可观的，在我搓了好久鼠标后，内存并没有明显异常。小范围的波动是有，但不是持续上涨。

**Comment by ping9719** [comment]
确实我测试不完全，感谢作者的建议。
我刚才测试500,1000,2000,3000，最高到了6.4M就不在增长了，没有内存的问题，CPU（i510）也占用最高9.3%
