### ISSUE TITLE
使用Named Pipe模式，我如何确认服务端是否开启？

### ISSUE THREAD

**Issue by ping9719** [HandyOrg/HandyIpc#26]
我测试在服务端没有开启的情况下，客户端的方法会一直等待直至服务端开启？
那么我如何在调用方法前，确认服务端已开启呢？

**Comment by ping9719** [comment]
我想到的办法就是去检测任务管理器里面是否有xxx进程，但是我觉得不是很合理吧？我觉得HandyIpc里面自带会好一点吧？
![image](https://user-images.githubusercontent.com/9651046/200461930-7c629689-46f3-4363-bf31-dba12083dade.png)

**Comment by DingpingZhang** [comment]
这个确实有考虑，但其实也是一个辅助功能，它和另一个需求是有联系的：检查服务器是否为单例。
也就是单例进程，这个一般用 `EventWaitHandle` 实现，参考：[ProcessController.cs](https://github.com/DingpingZhang/WpfExtensions/blob/master/WpfExtensions.Infrastructure/ProcessController.cs)

**Comment by ping9719** [comment]
才疏学浅，才看半天没有看明白，请问一下`ProcessController`怎么使用呢？
`ProcessControllerProcessController.IsDuplicateInstance("JgkljServe");`
不管运行了JgkljServe.exe还是没有运行，他都是返回的false

**Comment by DingpingZhang** [comment]
它核心原理是 `EventWaitHandle`，相当于一个可以在进程间共享的信号，你可以去查一下它的使用方法。

**Comment by ping9719** [comment]
感谢作者的解答，get到了新知识，但是它并不能解决问题，可能在库内部没有是否连接的方法前，我只能去检测进程。
我看的这篇文章：https://www.qxqzx.com/contents/674.html
他有一个问题，在服务端创建后在关闭，强制关闭等。。客户端还是返回的存在（应该是不存在）。
此`EventWaitHandle`我看官方文档是一般用于异步同步的。
